apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler
  namespace: system
data:
  # // TODO v1beta2 or v1beta1
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta2
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: discoblocks-scheduler
      plugins:
        filter:
          enabled:
          - name: PodScheduler
    leaderElection:
      leaderElect: false
