apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: metrics-proxy
        # Set runAsNonRoot to true once image has replaced
        image: nixery.dev/shell/frp
        command:
        - sh
        - -c
        - |
          cat <<EOF > /tmp/frps.ini
          [common]
          ; log_level = trace
          disable_log_color = true
          bind_port = 63535
          proxy_bind_addr = 127.0.0.1
          enable_prometheus = true
          user_conn_timeout = 5
          max_ports_per_client = 1
          max_pool_count = 1
          heartbeat_timeout = 10
          detailed_errors_to_client = true
          dashboard_addr = 127.0.0.1
          dashboard_port = 8000
          tls_only = true
          tls_enable = true
          tls_cert_file = /tmp/k8s-webhook-server/metrics-certs/tls.crt
          tls_key_file = /tmp/k8s-webhook-server/metrics-certs/tls.key
          tls_trusted_ca_file = /tmp/k8s-webhook-server/metrics-certs/ca.crt
          EOF
          trap exit SIGTERM ;
          while true; do frps -c /tmp/frps.ini & c=$! wait $c; done
        securityContext:
          privileged: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/metrics-certs
          name: metrics-cert
          readOnly: true
        ports:
        - containerPort: 63535
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 128Mi