
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: system
spec:
  ports:
    - port: 63535
      protocol: TCP
      targetPort: 63535
  selector:
    app: discoblocks
    app.kubernetes.io/component: discoblocks