# permissions for end users to edit diskConfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diskConfig-editor-role
rules:
- apiGroups:
  - discoblocks.ondat.io.discoblocks.ondat.io
  resources:
  - diskConfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discoblocks.ondat.io.discoblocks.ondat.io
  resources:
  - diskConfigs/status
  verbs:
  - get
