---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/finalizers
  verbs:
  - update
- apiGroups:
  - discoblocks.ondat.io.discoblocks.ondat.io
  resources:
  - diskConfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discoblocks.ondat.io.discoblocks.ondat.io
  resources:
  - diskConfigs/finalizers
  verbs:
  - update
- apiGroups:
  - discoblocks.ondat.io.discoblocks.ondat.io
  resources:
  - diskConfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses/finalizers
  verbs:
  - update
