apiVersion: v1
kind: Pod
metadata:
  labels:
    discoblocks: diskconfig-sample
  name: diskconfig-sample
spec:
  # hostPID: true
  terminationGracePeriodSeconds: 1
  containers:
  - name: alpine
    image: alpine:3.16
    command:
    - sleep
    - infinity
    volumeMounts:
    - mountPath: /host
      name: host
    securityContext:
      privileged: true
  volumes:
    - hostPath:
        path: /
      name: host