apiVersion: discoblocks.ondat.io/v1
kind: DiskConfig
metadata:
  name: diskconfig-sample-storageos
  namespace: default
spec:
  storageClassName: storageos
  capacity: 1Gi
  availabilityMode: ReadWriteSame
  # %d is optional, but will automatically appended for second drive if missing
  mountPointPattern: /usr/share/nginx/html/data
  podSelector:
    app: nginx
  policy:
    pause: false
    upscaleTriggerPercentage: 50
    maximumCapacityOfDisk: 2Gi
    maximumNumberOfDisks: 3
