apiVersion: discoblocks.ondat.io/v1
kind: DiskConfig
metadata:
  name: diskconfig-sample
  namespace: default
spec:
  storageClassName: storageos
  capacity: 1Gi
  availabilityMode: ReadWriteSame
  # %d is optional, but will automatically appended for second drive if missing
  mountPointPattern: /media/discoblocks/sample-%d
  podSelector:
    discoblocks: diskconfig-sample
  policy:
    upscaleTriggerPercentage: 50
    maximumCapacityOfDisk: 2Gi
    maximumNumberOfDisks: 3
    coolDown: 20s
    pause: false
