# in test don't use yet

name: end-2-end build

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
permissions:
  contents: read
  pull-requests: read
  actions: read
  security-events: write
  packages: write

concurrency:
  group: ci-e2e-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  golangci-lint:
    uses: ./.github/workflows/_gocilint.yml
  
  gosec-scanning:
    uses: ./.github/workflows/_gosecscan.yml
    
  image-build:
    uses: ./.github/workflows/_docker-build.yml
    needs: gosec-scanning

  image-vulnerability-scan:
    uses: ./.github/workflows/_trivy.yml
    needs: image-build

  kuttl:
    uses: ./.github/workflows/_kuttl.yml
    needs: image-build
