name: golangci-lint

on:
  workflow_dispatch:

permissions: read-all

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4b237a63e5299c390fb934f06848da715fdde07c
        with:
          version: latest
          args: --issues-exit-code=0
          only-new-issues: true
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

