name: Release Version

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  pull-requests: read
  actions: read
  security-events: write
  packages: write

concurrency:
  group: ci-release-${{ github.ref }}-1
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}
jobs:
  auto-pre-release:
    if: startsWith(github.ref, 'refs/tags/v') && (contains(github.ref_name, '-alpha.') || contains(github.ref_name, '-beta.'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: harden runner
        uses: step-security/harden-runner@9b0655f430fba8c7001d4e38f8d4306db5c6e0ab
        with:
          egress-policy: audit
      - name: checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 0
      - name: log in to ghrc.io
        uses: docker/login-action@1edf6180e07d2ffb423fc48a1a552855c0a1f508
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run e2e workflow
        uses: ./.github/workflows/e2e-on-pr.yaml
      - name: push images
        run: make docker-push
      - name: set since tag
        run: echo "SINCE_TAG=$(git describe --tags --always $(git rev-list --tags) | grep -e '^v[0-9]+*\.[0-9]+*\.[0-9]+*$' | head -1)" >> $GITHUB_ENV
      - name: generate release changelog
        uses: heinrichreimer/github-changelog-generator-action@6f5b9494dd265d6fb7243a10c53dc0169c55f247
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          base: .github/RELEASE_TEMPLATE.md
          sinceTag: ${{ env.SINCE_TAG }}
          simpleList: true
      - name: fix version in changelog
        run: sed -i "s/#VERSION#/${{ github.ref_name }}/g" CHANGELOG.md
      - name: create pre-release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          prerelease: true
          body_path: CHANGELOG.md
          files: |
            discoblocks-bundle.yaml
            discoblocks-kustomize.tar.gz

  auto-release:
    if: startsWith(github.ref, 'refs/tags/v') && !contains(github.ref_name, '-alpha.') && !contains(github.ref_name, '-beta.')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: harden runner
        uses: step-security/harden-runner@9b0655f430fba8c7001d4e38f8d4306db5c6e0ab
        with:
          egress-policy: audit
      - name: checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
        with:
          fetch-depth: 0
      - name: log in to ghrc.io
        uses: docker/login-action@1edf6180e07d2ffb423fc48a1a552855c0a1f508
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: run e2e workflow
        uses: ./.github/workflows/e2e-on-pr.yaml
      - name: push images
        run: make docker-push
      - name: set since tag
        run: echo "SINCE_TAG=$(git describe --tags --always $(git rev-list --tags) | grep -e '^v[0-9]+*\.[0-9]+*\.[0-9]+*$' | head -2 | tail -1)" >> $GITHUB_ENV
      - name: generate release changelog
        uses: heinrichreimer/github-changelog-generator-action@6f5b9494dd265d6fb7243a10c53dc0169c55f247
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          base: .github/RELEASE_TEMPLATE.md
          sinceTag: ${{ env.SINCE_TAG }}
          simpleList: true
      - name: fix version in changelog
        run: sed -i "s/#VERSION#/${{ github.ref_name }}/g" CHANGELOG.md
      - name: create pre-release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        with:
          prerelease: false
          body_path: CHANGELOG.md
          files: |
            discoblocks-bundle.yaml
            discoblocks-kustomize.tar.gz